force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>Trip-{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/number_of_participants__c.field-meta.xml
<CustomField>
    <fullName>number_of_participants__c</fullName>
    <label>number of participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>A venir</fullName>
            </value>
            <value>
                <fullName>En Cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchTripStatus.cls
global class BatchTripStatus implements Database.Batchable<SObject> {

    // Méthode start pour récupérer tous les voyages

    global Database.QueryLocator start(Database.BatchableContext bc) {

        return Database.getQueryLocator([
            SELECT Id, Start_Date__c, Number_of_Participants__c, Status__c, End_Date__c, Destination__c, Account__c, Opportunity__c, Name
            FROM Trip__c
            WHERE Status__c != 'Annulé' AND Status__c != 'Terminé'
        ]);
    }

    // Méthode execute pour vérifier le nombre de participants et mettre à jour le statut des voyages

    global void execute(Database.BatchableContext bc, List<Trip__c> scope) {

        List<Trip__c> ListTripsToUpdate = new List<Trip__c>();

        for(Trip__c trip : scope){

            if(Date.today() < trip.Start_Date__c ){

                trip.Status__c = 'A venir';
                ListTripsToUpdate.add(trip);
            }
            else if (Date.today() >= trip.Start_Date__c && Date.today() <= trip.End_Date__c ){

                trip.Status__c = 'En cours';
                ListTripsToUpdate.add(trip);
            }
             else if (Date.today() > trip.End_Date__c){ 

                trip.Status__c = 'Terminé';
                ListTripsToUpdate.add(trip);   
        }

        if(!ListTripsToUpdate.isEmpty()){
            update ListTripsToUpdate;
        }
    }
}

// Méthode finish pour envoyer une notification à l'administrateur avec le nombre de voyages mis à jour

    global void finish(Database.BatchableContext bc){
        
    }
}